### ISSUE TITLE
unexpectedly found nil while unwrapping an Optional

### ISSUE THREAD

**Issue by pfent** [TCA-Team/iOS#10]
while testing the app, I got an error in CafeteriaManager.swift, Line 78. `location` is `nil`

```
fatal error: unexpectedly found nil while unwrapping an Optional value
```

**Comment by mathiasquintero** [comment]
What? I never get errors with nil!!! I'm on it.
You ran it in the simulator? You probably didn't give it a location to simulate...

**Comment by pfent** [comment]
jup. Tried the emulator for the first time ever and I don't no nothing yet [I know nothing](https://www.reddit.com/r/thingsjonsnowknows).

But thanks for fixing anyways :sparkling_heart:

**Comment by mathiasquintero** [comment]
No Problem!
