### ISSUE TITLE
Chose which mensa to display in card

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#104]
Ideally this will be GPS based, as it is in the Android App - but for now let the user chose which mensa should be displayed on the featured page.

**Comment by mathiasquintero** [comment]
Right now it's gps based

**Comment by kordianbruck** [comment]
Alright, didn't know. I just got it from a student as a feedback. I'll let him know then. 

Are you using geofencing as well? Or are you simply doing a distance kind of thing?

**Comment by mathiasquintero** [comment]
Only distance. However, we could let the manager know which class you have right now and which mensa is closest.

Should we have that in the roadmap for both?

**Comment by kordianbruck** [comment]
I mean we could maybe add some fancy switching UI or something? Lets discuss this next monday.

**Comment by mathiasquintero** [comment]
Yeah. I just thought it would be cool if we could make it more context aware
