### ISSUE TITLE
Move sensitive Data to keychain

### ISSUE THREAD

**Issue by mathiasquintero** [TCA-Team/iOS#107]
Update Sweeft to 0.8.1 and update `PersistentUser` to use Keychain. 

```Swift
struct PersistentUser: ObjectStatus {
    static var storage: Storage = .keychain
    static var key: AppDefaults = .login
    static var defaultValue: PersistendUserData = .no
}
```

*And* store the data for the BookRentals API in the same way or even inside the persisted user

**Comment by TG908** [comment]
@mathiasquintero have you used the objc keychain wrapper for your implementation or did you write your own?

**Comment by mathiasquintero** [comment]
Wrote my own https://github.com/mathiasquintero/Sweeft/blob/master/Sources/Sweeft/UserDefaults/Keychain.swift

I needed it on another project as well. Plus I wanted to learn how that API works

**Comment by TG908** [comment]
Great so we can get rid of the objective c

**Comment by mathiasquintero** [comment]
This was already done. We should probably introduce a compatibility layer so that we don't have lot's of people signing in again
