### ISSUE TITLE
Handle TUMOnline Links

### ISSUE THREAD

**Issue by nerdsupremacist** [TCA-Team/iOS#116]
We could register for the TUMOnline URLs so that when someone opens a link (eg: in Mail) it should open the App instead of Safari

**Comment by kordianbruck** [comment]
I mean yes, we could. But this would not be an improvement over opening it in the browser, as the user still has to login.

**Comment by mathiasquintero** [comment]
Well, we wouldn't have to log in if we have permissions to open the grades, calendar, etc.

If you get an email about your new grades and click on the link the app would show you your grade.

**Comment by kordianbruck** [comment]
Yea, that would be nice. Well if you can catch this so exactly, that would be great. 

Another idea: you can still do the login part for the user, as you are saving the credentials for opac no?

**Comment by mammuth** [comment]
The mapping between TUMOnline's URL scheme and our views might be tricky I think.

> Another idea: you can still do the login part for the user, as you are saving the credentials for opac no?

True, that'd be a useful feature! 👍 Beside just catching links, we could also add TUMOnline to the app as a webview in order to auto-login the user.

**Comment by TG908** [comment]
Theres is not much to handle

**Comment by TG908** [comment]
Unfortunately the focus of the app should not be to override TUMonline but to extend its features. Handling those links would mean that we are implementing those features in a compatible manner with all extensions. This is not currently possible
