### ISSUE TITLE
Add MVV Information

### ISSUE THREAD

**Issue by mathiasquintero** [TCA-Team/iOS#12]
- [ ] Create a Card for the MVV Info and a Detail View. 
- [ ] Perhaps even allow for search in the Universal Search Screen...

**Comment by mammuth** [comment]
- [ ] Card for MVV malfunctions ("Störungsticker") #25

**Comment by kordianbruck** [comment]
@mammuth that is a simple News card

**Comment by TG908** [comment]
The card could also display the departure times from the campus
