### ISSUE TITLE
User Details don't always match the exact user

### ISSUE THREAD

**Issue by mathiasquintero** [TCA-Team/iOS#121]
See Ticket #880490

So far we get the user details by a search with the exact name and filter the list a bit afaik. Perhaps tinker with the filtering a bit or try to fetch it from the LRZ id.

**Comment by mammuth** [comment]
Tickets:
https://tca.exgen.io/scp/tickets.php?id=213

**Comment by arisun** [comment]
I would like to contribute on this project. Could you please help picking the first issue to resolve.

**Comment by mathiasquintero** [comment]
@arisun if you want you can take a look at this very issue. The reason we haven't gotten around to it is that it will take a bit of reverse engineering of the TumOnline API. 

The reason this happens is we search for a user with the exact name of the logged in user and show their details. This obviously leads to conflicts, because you guessed it 2 people can have the same name.

Option 1: see if we can get a hold on the LRZ ids of the search results and only match the ones with the exact same LRZ Id as the logged in user. Instead of blindly taking the first one.
Option 2: check if there's another endpoint we can request for this.

The relevant files are: 

https://github.com/TCA-Team/iOS/blob/master/TUM%20Campus%20App/UserDataManager.swift
https://github.com/TCA-Team/iOS/blob/master/TUM%20Campus%20App/PersonSearchManager.swift

**Comment by mathiasquintero** [comment]
@arisun wait, you're not a student? Ok. This is gonna be difficult. @mammuth how are we handling cases like this?

**Comment by kordianbruck** [comment]
Unfortunately there are no test users. But alumnis can still login into tumonline and use the app

**Comment by kordianbruck** [comment]
https://tca.exgen.io/scp/tickets.php?id=264

**Comment by kordianbruck** [comment]
@mathiasquintero is there any solution for this. We are getting many support tickets mentioning this issue, which does not really seem that problematic to me to resolve it? Or is it?

**Comment by mathiasquintero** [comment]
@kordianbruck Ok. Do you know exactly what Android is doing in this use case. Or are they having the same issue as well?

**Comment by kordianbruck** [comment]
@pfent ?

**Comment by pfent** [comment]
Ah, thanks for pinging me, I could had clearified this much earlier.
For starters I'd suggest to not guessing the names, when there's no exact match :ghost: 

I think for the exact name you can just use the `id` endpoint and show that name to the user.

To get the person details, we [search for the person like you do](https://github.com/TCA-Team/TumCampusApp/blob/caf2eea586f6181a170b8398689ee67511af03fb/app/src/main/java/de/tum/in/tumcampusapp/activities/wizard/WizNavCheckTokenActivity.java#L142), but only if we get a unique match, we actually display the picture of the user.
You could also manually filter out users, that no not have the exact searched name, but I couldn't be bothered to implement that, yet.

@xsrf @kordianbruck  a TUMonline endpoint to get the own `pIdentNr` for the personsearch would be awesome

**Comment by mathiasquintero** [comment]
Ok. For now I just won't set any attribute other than the name if there's more than one result.
