### ISSUE TITLE
App does not return to login screen after token is deleted in TUM Online

### ISSUE THREAD

**Issue by TG908** [TCA-Team/iOS#122]
When I deleted all my tokens in tum online, the app didnt display the login screen nor displayed me as a Stranger. The app crashed when i tried to click on my name. (#118) The calendar kept working (cache).

**Comment by kordianbruck** [comment]
Nice! I thought I tested this already and was amazed by the claims last monday, when someone said it would logg off automatically :P

**Comment by TG908** [comment]
The user model needs some more work...
