### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#123]
There are several users who complain not being able to get to the cards view after clicking authorization after enabling the tokens.

**Comment by mammuth** [comment]
Related tickets:
http://tca.exgen.io/scp/tickets.php?id=204
http://tca.exgen.io/scp/tickets.php?id=207
(Send them mails when we fixed this)

**Comment by mammuth** [comment]
We should try to fix that asap since we already got a couple of more mails now that the semester starts.

@mathiasquintero If I remember correctly you told me once you found the cause for this? Can't remember what it was 🙈

**Comment by mathiasquintero** [comment]
Hahaha me neither. Damn. We'll have to check it out

**Comment by kordianbruck** [comment]
Wasn't this the problem that we just fixed in that pull request?  #143

**Comment by mammuth** [comment]
That's why I was asking for the cause. :blush:

Wasn't there the problem that the token was requested whenever the login vc was opened or something like that? So when people activated one token in TUMOnline and came back to the app, it sometimes already had requested another one? Or is that not the current behavior anymore / got fixed?

**Comment by mammuth** [comment]
@mathiasquintero could you dig into this during this week so we can release a new version at the weekend? We get a lot of support mails which are caused by our login flow.

**Comment by mammuth** [comment]
Related / Similar changes: https://github.com/TCA-Team/iOS/issues/131

**Comment by mammuth** [comment]
Resolved via #171
