### ISSUE TITLE
Picker views don't hide automatically

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#124]
The picker views don't hide automatically when they are open and the user navigates back. This occurs at least with the following views (add more when you find/remember them):
- Cafeteria Chooser
- Study Room Buildings
- Room Finder 
- ...

Related support tickets (tell them via mail when this is fixed):
- http://tca.exgen.io/scp/tickets.php?id=209

**Comment by TG908** [comment]
Also the arrow doesn't update when you dismiss the picker by tapping anywhere
