### ISSUE TITLE
Confirm with the user, that a LRZ id is correct

### ISSUE THREAD

**Issue by pfent** [TCA-Team/iOS#131]
Got feedback from someone setting up the app:
After entering the last character of ones LRZ id, the app immediately continues to the next screen.

This is problematic due to possible typos in that ID:
A token for a random user is generated. Due to the TUMonline cap of 10 tokens per user, we generally don't want to do that.

Possible solutions:
* Confirm with the user, that this a token for this ID will be generated. (Would break the flow, ugly)
* Indicate, that a token is being generated and only after a one or two seconds proceed to actually requesting the token and continuing to the next screen (something like [this](https://developer.android.com/training/wearables/ui/confirm.html#confirmation-timers))

**Comment by mammuth** [comment]
Right. @mathiasquintero talked about reworking the login flow, and I think that's one of the things that we talked about to change 👍

**Comment by mammuth** [comment]
Resolved via #161
