### ISSUE TITLE
Add app store link to README.md

### ISSUE THREAD

**Issue by rodalfus** [TCA-Team/iOS#134]
Currently, the readme for this project does not include a link to the app store, despite it being the first thing that is shown when entering a repository on Github. To save any interested users or developers the work of having to manually search the app store, the readme should include the following link: https://itunes.apple.com/app/id1217412716, ideally in the first section.

**Comment by rodalfus** [comment]
If possible, I'd like to "implement" this, to get used to the collaboration process and be able to add more relevant (code-)fixes in the future.

Did I understand correctly that the steps needed would be:

1. Fork the repository
2. Branch off of `master`
3. Implement change
4. Create a pull request from my fork

I'm somewhat new to being a collaborator on an open-source project so please forgive my ignorance.

**Comment by mammuth** [comment]
Yes, that's exactly the way it's intended! 👍

**Comment by rodalfus** [comment]
Short follow-up: Is there any way to signal that I would like to take responsibility for an issue I create or more general any issue?

**Comment by mammuth** [comment]
> Is there any way to signal that I would like to take responsibility for an issue I create or more general any issue?

Yes, we can assign you to the issue 😉
