### ISSUE TITLE
Login flow needs improvement

### ISSUE THREAD

**Issue by lukaskollmer** [TCA-Team/iOS#139]
**Problem:**

Selecting "I don't have an LRZ-ID" in the login screen will load the "Main" storyboard and present the `CampusTabBarController` on top of the login view controller.
This works fine the first time, but due to how the login screen is presented (reassigning `UIApplication.shared.keyWindow?.rootViewController` rather than simply calling `UIViewController.present(_:animated:completion:)`), a new instance of `CampusTabBarController` is created every time you skip login.
This means that - if you open and dismiss the login screen a couple of times - the app's view hierarchy gets unnecessarily convoluted, which in turn consumes a lot of memory:

![](https://files.lukaskollmer.me/embed/tum-campus-app-bad-view-hierarchy.png?v=2)

**Solution:**

The obvious fix is to
1) Re-implement the login flow and present the `LoginViewController` by calling `present(_:animated:completion:)` on the `CampusTabBarController`
2) Simply call `dismiss(animated:completion:)` on the `LoginViewController` when the skip button is pressed
3) Use singletons (loading all view controllers from their storyboards every time you're about to present them is an incredibly inefficient approach)

**Comment by TG908** [comment]
You‘re right would you mind putting this into a PR soon?

**Comment by lukaskollmer** [comment]
I'll see what I can do but I'm new to the codebase so this might take a while

**Comment by mobi-robert** [comment]
Hi, I'd like to implement this, if that's alright.

**Comment by TG908** [comment]
Sure go ahead.

**Comment by mammuth** [comment]
Closed via #143
