### ISSUE TITLE
MVV?

### ISSUE THREAD

**Issue by lukaskollmer** [TCA-Team/iOS#140]
Turns out I have a lot more free time than anticipated

How exactly should the MVV feature be designed? IMO there's a lot of things this could include:
- list of nearby stations
- upcoming departures
- upcoming departures at the nearest station (maybe in one of these cards?)
- service interruptions (maybe show a card that lists all lines that currently experience interruptions?)

I've been working on [something very similar](https://github.com/lukaskollmer/Abfahrt) as a side project over the past couple of weeks, so adding upcoming departures/nearby stations shouldn't be too difficult.

**Comment by mammuth** [comment]
You can always check out how the [android app](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/managers/TransportManager.java#L38) is approaching certain features. Furthermore you can probably use the same API's :wink: 

Btw, there might be some [related issues](https://github.com/TCA-Team/iOS/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20mvv).

**Comment by lukaskollmer** [comment]
using the same API as the android app doesn't seem like a good idea since it's HTTP only, meaning that you'd need to register an ATS exception, which apple probably won't like

one more question:
how can i add/register a card to be displayed in the cards list on the main screen (i'm thinking about adding 2 cards, one for upcoming departures at the closest station and one with general information about service interruptions)

**Comment by TG908** [comment]
We already have an ATS exception in place.
