### ISSUE TITLE
Xcode 9 + Swift 4 Migration

### ISSUE THREAD

**Issue by mathiasquintero** [TCA-Team/iOS#144]
We will need to think about migrating to Xcode 9 and Swift 4 pretty soon.

Big questions:
- Which deps will we have to update ourselves?
- Which should run in Swift 4 and which in the 3.2 compatibility mode?
- How can we guide the pod script that creates the targets to configure the correct build settings for these projects and not bump them all blindly to Swift 4?

**Comment by TG908** [comment]
I think we can get rid of:

- PZPullToRefresh (not only code outdated also ui design)
- FoldingCell (replace with apple news like design)

**Comment by lukaskollmer** [comment]
We'll need to update `SWXMLHash` to 4.0.0 to get around [this issue](https://github.com/drmohundro/SWXMLHash/issues/140)

>/Users/lukas/Developer/iOS/Pods/SWXMLHash.XMLIndexer:72:22: Invalid redeclaration of 'Element'

(Swift 4 added `associatedtype Element` to `Sequence` which clashes with an enum case in SWXMLHash)

**Comment by TG908** [comment]
@mathiasquintero this can be closed right?

**Comment by mathiasquintero** [comment]
Oh yeah this can be closed
