### ISSUE TITLE
Hide "Service" cell on "More" screen

### ISSUE THREAD

**Issue by rodalfus** [TCA-Team/iOS#147]
Currently, when tapping on "Services" in the more tab, a popup is shown, indicating that the feature is not implemented yet. It is not clear to me, what this feature should do and what the current development status of it is.

Unfortunately I don't have an Android device, so I'm not able to check how the Android app behaves here (or whether or not it even exists).

![simulator screen shot 7 oct 2017 at 21 57 23](https://user-images.githubusercontent.com/11002160/31311340-b7a72c4e-abaa-11e7-8b76-119f8ab14f7f.png)

**Comment by kordianbruck** [comment]
Yea, this should be disabled until we implement it. In Android we have a Silence Service and a Background service. The first one mutes your phone during lectures and the second one syncs any data in the background.

**Comment by lukaskollmer** [comment]
@kordianbruck The mute during lectures thing won't be possible on iOS anyway and I don't think background data sync on iOS needs a separate setting since you can toggle Background App Refresh on an app-by-app basis in Settings.app. IMO the entire "services" section can be removed on iOS

**Comment by kordianbruck** [comment]
Yea, I know, so thats why we should remove it till someone wants to tackle this issue ;)

**Comment by rodalfus** [comment]
Sure, I’ll take care of it.

**Comment by rodalfus** [comment]
@kordianbruck Should we keep the alerts for _Default Campus_ and _MVV_ or remove those as well?

**Comment by kordianbruck** [comment]
@rodalfus I'm not sure what those are - care to explain? (I think those are not implemented either, so then we should also hide them.)

**Comment by rodalfus** [comment]
Exactly, both not implemented (currently). #119 seems to have started progress on the _Default Campus_ functionality. Just saw that #141 implements the _MVV_ functionality, though.

**Comment by kordianbruck** [comment]
Yea, lets hide the default campus for now until that gets merged. Thanks for looking out for this!

**Comment by TG908** [comment]
done
