### ISSUE TITLE
Token not correctly propagated to managers after login

### ISSUE THREAD

**Issue by rodalfus** [TCA-Team/iOS#150]
Steps to reproduce:
- Log out of application if logged in
- Log in to application
- Go to "More" tab
- Check if your name is displayed (it won't be)
- Force quit and restart application
- Check if name is displayed in "More" tab (it will be)

This issues seems to been introduced with #143 (sorry!). Furthermore, the logs suggest that the token used by the application to get the user is incorrect until forcing a restart. Perhaps the reason for this can be found in one of the `viewDidLoad`s or `init`s of a view controller that was previously reinitialised (just trying to reason about this - might be something totally different).

This issue should be fixed before a new version is uploaded to the app store.

**Comment by rodalfus** [comment]
Ok, so I think we can fix this in the following way: add a reference to the `TUMDataManager` used in the `MoreTableViewController` to the `WaitForTokenViewController`. Update the `dataManager`'s user once we get a new one in the `MoreTableViewController`. Also, request the user's user data there. Add a callback to `TUMDataManager.getUserData` and update the `MoreTableViewController`'s views when that is called. 

Am I missing anything here? Does anyone have a better idea?

**Comment by rodalfus** [comment]
@mathiasquintero

**Comment by mathiasquintero** [comment]
Add a delegate to the MoreTableViewController and then you'll have a reference to DataManager through the delegate. I don't know about updating the data everytime, though. Maybe only if it's nil

**Comment by mammuth** [comment]
Resolved by #170
