### ISSUE TITLE
Pasting into the login ID textfields is wonky

### ISSUE THREAD

**Issue by rodalfus** [TCA-Team/iOS#151]
**Steps to reproduce**:
(1):
- Open login screen
- copy your ID (e.g. ga12ab)
- paste the ID in the first textfield

You will see that the whole ID is pasted into one textfield.

(2):
- Open login screen
- Input the first two characters of your ID and then select the first textfield again
- Input another character

You will see that it is possible to input more than the expected two characters into the textfield.

**Definition of Done**:
- Every textfield has atmost the specified number of characters in its text
- Pasting into one textfield can "overflow" text to the next ones

**Comment by rodalfus** [comment]
@mathiasquintero I believe that a solution that does not require third-party libs and works as expected (as I believe the one I implemented does) is preferable to using a third-party (especially) UI component, which we'd have to make sure is up-to-date and might just be abandoned in a year or so.

**Comment by mathiasquintero** [comment]
Actually I was thinking that maybe at this point UIKit may have a solution

**Comment by rodalfus** [comment]
I'll have a look, but honestly I doubt that there is a native UIKit solution for this. Have not come across one until now at least ;)
