### ISSUE TITLE
Show an activity indicator while loading a room map

### ISSUE THREAD

**Issue by lukaskollmer** [TCA-Team/iOS#155]
Loading a room map over a slow connection (EDGE, wifi with ~10k other users) can take a very long time.

We should show some sort of loading indicator ([`UIActivityIndicatorView`](https://developer.apple.com/documentation/uikit/uiactivityindicatorview)/[`MRProgress`](https://github.com/mrackwitz/MRProgress)/etc) while the image is loading.

**Comment by mathiasquintero** [comment]
Actually we need this pretty much everywhere where we don't have a refresh coordinator

**Comment by TG908** [comment]
done
