### ISSUE TITLE
Release this Week

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#157]
@TCA-Team/ios please can someone finally determine in this issue, what needs to be done until we can release a new version? We wanted to do this months ago. Please post relevant issues/prs in this issue, so that we can have a overview. 

**We need to release by the end of the week to finally fix those login issues and a thousand tokens being generated!**

**Comment by rodalfus** [comment]
#150 should definitely be fixed. I think I‘ll have a little time to have a look at this later today but can’t make any guarantees.

**Comment by mammuth** [comment]
Important Issues / PR's:
- https://github.com/TCA-Team/iOS/issues/123
- https://github.com/TCA-Team/iOS/issues/150

**Comment by TG908** [comment]
I'll try getting the ui ready as soon as possible...

**Comment by mathiasquintero** [comment]
https://github.com/TCA-Team/iOS/pull/161 should also go in

**Comment by mammuth** [comment]
> #161 should also go in
Yes. It's tracked via the 1.2 milestone 👍

**Comment by kordianbruck** [comment]
Just released. Thanks to @mathiasquintero @TG908 @mammuth @rodalfus @larryzuo for fixing so many bugs and getting this done! Great Effort!
