### ISSUE TITLE
Calendar does not show any events

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#158]
I think we don't have an issue for that bug yet. There are many reports about this in the ticket system. They state they are able to see their lectures and stuff like that, but their calendar is empty.

**Comment by mathiasquintero** [comment]
I wouldn't necessarily call this a bug.
We need to add a button to force refresh the calendar, instead of the user having to wait a week for it to refresh

**Comment by mammuth** [comment]
So it's due to the caching in the app? Then I'd still call it a bug if the cache period is a week, since that's no proper cache rate in my opinion.

There are also un-periodic events the user is not aware of, which are placed spontaneously into the calendar by TUM Online. Receiving this event one week late might be bad as well...

**Comment by kordianbruck** [comment]
@mammuth we have to respect TUMonline here. Fetching the calender is one of the most impacting operations and requires a lot of computation time on their end. One week is resonable as mostly the lectures change once at the beginning and then some get canceled. But almost never are there any lectures added short hand.

**Comment by mammuth** [comment]
Wut, TUM Online wants us to have a calendar that's in the worst case one week out of date 😮 

But okay, refresh button it is...

**Comment by mammuth** [comment]
Resolved by #162
