### ISSUE TITLE
Removing a card in edit mode freezes app

### ISSUE THREAD

**Issue by TG908** [TCA-Team/iOS#159]
In the version of the app i am working on (branch: 82-NewDesign2), the app freezes when removing a card via the edit menu. @mathiasquintero is it possible that this has something todo with Sweeft. Is anyone else experiencing this (maybe with swift 4 or sweeft 0.13)??

```
extension UserDefaults: StorageItem {
  
    func set<C>(_ value: C?, forKey defaultName: String) where C : Decodable, C : Encodable {
        
        guard let value = value else { return set(nil, forKey: defaultName) }
        let encoder = PropertyListEncoder()
        encoder.outputFormat = .xml
    --> let data = try? encoder.encode(value)
        set(data, forKey: defaultName)
    }
```

This is where the app hangs and uses more and more memory / cpu. The last line is recursively calling this function with increasing amounts of data.

**Comment by mathiasquintero** [comment]
Yeah. I saw this. I'll fix it

**Comment by mathiasquintero** [comment]
Ok. I think I have a fix. Please update to Sweeft 0.13.1

**Comment by mathiasquintero** [comment]
Never mind. Tested it. Didn't work :(

**Comment by mathiasquintero** [comment]
Aha. Finally got it. The fix will be out in a min. 0.13.2
