### ISSUE TITLE
Import calendar into Apple Calendar

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#160]
We could add an easy way for importing the TUM Online calendar into the Apple Calendar (via URL) if this is possible.

**Comment by kordianbruck** [comment]
I don't think you can get the URL via the API. You only get the events as a XML file. Otherwise this would also make sense: https://github.com/kordianbruck/TumCalProxy/issues/8

**Comment by mammuth** [comment]
Ah, good to know! Then we might integrate a hint to the CalProxy 👍

**Comment by TG908** [comment]
Calendars can also be setup using profiles

**Comment by mathiasquintero** [comment]
The profile is a bit too hacky though. Because you have to open it somehow. And the system won't allow to open a file URL of the system... My best guess would be starting a local WebDav server with an autogenerated Profile.

Nah. I don't like it.
Apple surely has an API for the calendar

**Comment by TG908** [comment]
We cannot get the ical url token
