### ISSUE TITLE
The TU Film announcements shouldn't appear in the news

### ISSUE THREAD

**Issue by TG908** [TCA-Team/iOS#165]
Since we are not going to refactor the news api we somehow need to make sure, that the tu film movies won't show up in the news card.

**Comment by kordianbruck** [comment]
Why should they not appear in the news? 
The idea is to show one card for each news source. Thats how its done in Android.

**Comment by TG908** [comment]
Then we should work on making one card for each news source. @mathiasquintero might have already done this in #167

**Comment by mathiasquintero** [comment]
Sure! We can do it!

**Comment by TG908** [comment]
duplicate see #220
