### ISSUE TITLE
Buggy XML parsing

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#17]
The current implementation works, but its not really a great solution to first parse the xml and then cast it to json. 

We need to improve the logic and make it neat and tidy to not have "spaghetti code"

**Comment by mathiasquintero** [comment]
Hahaha, Damn I forgot about that. I was switching everything to another library...

**Comment by kordianbruck** [comment]
Whats that new library? Anything I can do? Lets tackle these issues together :+1:

**Comment by mathiasquintero** [comment]
Ah I'm almost done!

**Comment by kordianbruck** [comment]
kk

**Comment by mathiasquintero** [comment]
@kordianbruck while I have the project open ;) anything else you may have in mind?

**Comment by kordianbruck** [comment]
Finish GCM and the alamierung, so we can publish the first version :+1: 

5 minute job, right? :tada: :tanabata_tree:

**Comment by mathiasquintero** [comment]
Obviously!!!

**Comment by mathiasquintero** [comment]
Handled by https://github.com/TCA-Team/iOS/commit/427c93002339473e5ae79e27ddce63f990652fff
