### ISSUE TITLE
Remove TabBar

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#179]
As suggested by @TG908, the tabbar is kind of unneeded. 

Possible other ways to get to the more view:
- We could add the profile image to the toolbar which links to it
- some kind of swipe / dropdown similar to snapschat ( @mathiasquintero  idea)
- Your sexy idea here

**Comment by TG908** [comment]
The toolbar already has the search thingy

**Comment by mammuth** [comment]
> The toolbar already has the search thingy

Yeah, we have room here to discuss what to move where 😊 Anything against moving the search icon to the left and having the profile image on the right?

**Comment by TG908** [comment]
@mammuth The edit button is on the left 😄. We could have 2 buttons on one side of course.

**Comment by mammuth** [comment]
> The edit button is on the left 

I know the current state, I'm here to discuss possibilities^^ I could imagine that the edit cards button isn't that important and we might add that to the moreview for example.

**Comment by rodalfus** [comment]
> If not, it's probably wasted space.
@mammuth For iOS 11 users we could go for the enlarged navigation bar and hide the search bar beneath that (see Mail.app).

**Comment by TG908** [comment]
One idea would be get rid of the edit button and put the no cards cell always on the bottom.

**Comment by TG908** [comment]
@rodalfus i like your idea its also quite simple
```
let search = UISearchController(searchResultsController: nil)
search.searchResultsUpdater = self
self.navigationItem.searchController = search
```

**Comment by TG908** [comment]
I will just have a go at it. Will also include large titles.

**Comment by mathiasquintero** [comment]
@mathiasquintero Check if you can get the image in the large title view instead of the navigation bar title view
