### ISSUE TITLE
Release first version in app store

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#18]
I'm currently working with the guys from the ITSZ to get an account rolling, so we can publish the app.

Hope to have everything set up by next week, so we can publish a first version starting with august.

**Comment by 13XxM1CHA3lxX37** [comment]
I'm trying the same, but still did not get a response from them. Any updates on your side regarding this)

**Comment by kordianbruck** [comment]
Please do not publish the app yourself. This will only lead to troubles for me to get this into the app store. I'm on it and have the partners contact info. I will check in again with them tomorrow in order to see what happened in the mean time.

**Comment by 13XxM1CHA3lxX37** [comment]
With the same I did not mean publishing, but an enrollment at the iOS Developer University Program (mostly for testing purposes concerning certificates). Would also not be very purposeful as I did not contribute to the app.
That's good to hear. To me it seemed like you ran into problems as the thread looked a little orphaned, so I just wanted to ask :)

**Comment by mathiasquintero** [comment]
Testing without certificates is not difficult. Since iOS 9 you can do it with a simple apple id

**Comment by kordianbruck** [comment]
@mathiasquintero I'm getting the problem that the package is already registered. Any thoughts on that? @mammuth also talked to you about this - can you please elaborate on what the result of your private discussion was, so I can help with getting this published?

I think my account ist now unlocked for the Dev Program, but unsure about the next steps. Any tipps?

**Comment by mathiasquintero** [comment]
Just change the Bundle Identifier a bit on your machine. Then it should work. The best way to not get these issues is for all of us to get on the university team so that we have the same signing identity

**Comment by kordianbruck** [comment]
@mathiasquintero @TheZoker please send me your apple IDs via mail

**Comment by 13XxM1CHA3lxX37** [comment]
I still did not even get a reply by the TUM Cmit Team... How did you get your evaluation?

**Comment by kordianbruck** [comment]
The CMIT Team is currently not adding any students. They are working things out on how to police this and they don't want to be responsible for any published apps.  Don't expect a reply, they don't answer emails usually.

**Comment by 13XxM1CHA3lxX37** [comment]
Oh okay. Thanks for the Information, that explains it.
Then I suppose I fell for an outdated guide.

**Comment by kordianbruck** [comment]
That guide in the app wiki is from ancient times. No one knows why it is there. It should really be removed.

**Comment by mathiasquintero** [comment]
@kordianbruck what's the status on this? I actually just got a Developer Membership recently. If it's too much trouble with the university I can release it

**Comment by kordianbruck** [comment]
@mathiasquintero did you get a company license?

**Comment by mathiasquintero** [comment]
I got the regular one. If I release it, it would be under my name. But we can all work with it

**Comment by kordianbruck** [comment]
I'm getting a company license. I think I can finally enroll next week after many emails between various parties. University is a no go on all front unfortunately.

If I can't get it by next week, I'll come back to your offer. Thanks @mathiasquintero

**Comment by mathiasquintero** [comment]
@kordianbruck you mean the enterprise one? There's no need. That's thrice as expensive and is for releasing in-house software. Which we are not doing

**Comment by kordianbruck** [comment]
Let me check that out first plox - I already got all the formalities done. Just waiting for some databases to update.

**Comment by kordianbruck** [comment]
I finally got the submission through. It can only be a thing of weeks now. As far as I know it costs the same amount of money.

**Comment by kordianbruck** [comment]
@mathiasquintero please send me your apple id - we can start deployment right away.

**Comment by mathiasquintero** [comment]
me@quintero.io

**Comment by kordianbruck** [comment]
![img_20170320_133237](https://cloud.githubusercontent.com/assets/298860/24100069/b15cb9de-0d72-11e7-95bc-42927b757b98.jpg)

Any ideas?

**Comment by mathiasquintero** [comment]
My first instinct would be:
- Clean Build
- `rm-rf ~/Library/Developer/Xcode/DerivedData/*/`
- `pod repo update`
- `pod install`
- `pod update`

**Comment by mathiasquintero** [comment]
I might have misspelled something but you get it. I'm on my phone

**Comment by kordianbruck** [comment]
Except I don't have pods installed and can't get it on this managed mac - Clean Build didn't help.

**Comment by mathiasquintero** [comment]
Cleaning DerivedData didn't help? That always helps

**Comment by kordianbruck** [comment]
Annnnnnnd we're live:
https://itunes.apple.com/us/app/tum-campus-app/id1217412716?l=de&ls=1&mt=8

**Comment by mammuth** [comment]
<img width="886" alt="screen shot 2017-04-01 at 23 18 08" src="https://cloud.githubusercontent.com/assets/3121306/24582507/a003e8d8-1731-11e7-93df-bc1ed0834b85.png">

Fun fact: 
Apple didn't even review the app. 🙈 

 
In order to use the app, they'd need to login to TUMOnline with the test account we provided them and set the permissions for a token. 
They never logged in to do so (all those login attempts have been me and probably the guy who created the test account)

**Comment by kordianbruck** [comment]
hahaha - I didn't even check. But then again we filled out the form so perfectly the first time, that they didn't bother really...
