### ISSUE TITLE
Compiling not possible

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [TCA-Team/iOS#19]
Sadly I'm not able tu build the app. Would be nice if there will be an update so that you can compile the app at least
![2016-10-30 4 57 23](https://cloud.githubusercontent.com/assets/20713070/19834399/88c047f4-9e5d-11e6-94ae-bffd52a8eb56.png)

**Comment by mathiasquintero** [comment]
Just fixed it with the mother of all commits. There might be some new bugs as a side effect though
