### ISSUE TITLE
Large Titles?

### ISSUE THREAD

**Issue by TG908** [TCA-Team/iOS#190]
What is your opinion on the large titles from iOS 11. Should we include them.

I think we should to keep our app's look as close as possible to other ios 11 apps. **With one exception: CardTableView** since we don't have a proper title for this vc (maybe someone of you guys knows a way to make the image move up like text).

**Comment by lukaskollmer** [comment]
This probably won't work on the `CardViewController` since we're using a custom `titleView` (the TUM logo). All other VCs should be fine
