### ISSUE TITLE
Calender Freeze

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#193]
"Leider gibt es immer noch Probleme mit dem Kalender - Wenn man zwischen Tagen hin und her wechselt bleibt die App oft eingefroren"

Feedback from a user. Are you parsing it on each swipe?

**Comment by mathiasquintero** [comment]
We are not parsing on each swipe. We parse whenever the screen is opened.

**Comment by kordianbruck** [comment]
That with the parsing was just an idea from my side - but it seems that  its really not performing so well.
