### ISSUE TITLE
Let's do another release on Sunday

### ISSUE THREAD

**Issue by TG908** [TCA-Team/iOS#194]
Planned Features (would close 11 issues and 4 PRs !):

- [x] #192 Remove Tab Bar
- [x] #167 network refactor
- [ ] #119 add default campus (needs work)

Anything else?

**Comment by mathiasquintero** [comment]
I don't know about the plans feature PR. I still don't like us shipping PDFs hardcoded with the app

**Comment by kordianbruck** [comment]
@mathiasquintero the plans should be downloaded from the Web. I can create an API for that. You on board? => Issue in Backend please

**Comment by TG908** [comment]
I think we should do a release every week. The new cards will be in next weeks release.

**Comment by mathiasquintero** [comment]
@TG908 is excited! Last release took a lot of work and I'm pretty busy these days so maybe slow down ;) 

I think the first three should be doable
