### ISSUE TITLE
Add refresh button to everything that is cached

### ISSUE THREAD

**Issue by mathiasquintero** [TCA-Team/iOS#196]
In the 1.2 we introduced a refresh button to update the cache of the calendar.

In PR: #167 we are caching a whole lot more of stuff.

We will need a lot more buttons.
To know what is being cached just check for implementations of `CachedManager`

**Comment by kordianbruck** [comment]
Think this will be redundant, if we just use pull to refresh everywhere to clear the cache for the current view? Might even be the best idea from a usability point of view.

**Comment by mathiasquintero** [comment]
Perhaps add pull to refresh where it's easy to implement and the rest we do the refresh button...
