### ISSUE TITLE
Add search bar to TUM.sexy redirects

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#198]
As the TUM.sexy redirects are growing - add a search bar to the view which filters the list of redirects.

**Comment by mathiasquintero** [comment]
I'd suggest showing them in the regular search as well

**Comment by mathiasquintero** [comment]
Suggestion: Let TUMSexyManager implement SearchManager and filter links locally...

**Comment by mathiasquintero** [comment]
This is my simples solution: https://github.com/mathiasquintero/Fuzzi

Which should allow us to search for both the domain and the description
