### ISSUE TITLE
Pods are not in gitignore

### ISSUE THREAD

**Issue by mathiasquintero** [TCA-Team/iOS#20]
I just noticed that the pods are not in the gitignore.

First we have to remove all the dependency sources.
Then we have to add the pods to the gitignore

**Comment by TheZoker** [comment]
Quoting the Cocopods Devs here:

> We recommend against adding the Pods directory to your .gitignore. However
> you should judge for yourself, the pros and cons are mentioned at:
> https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control

**Comment by mathiasquintero** [comment]
I'm mainly for adding them to gitignore for the sake of preventing merge conflicts. And I'm sure we all have cocoapods installed so it really isn't a problem... It's not necessary, but it feels like checking in the node-modules/ folder in a NodeJS project.

**Comment by kordianbruck** [comment]
http://stackoverflow.com/questions/9446644/what-goes-into-your-gitignore-if-youre-using-cocoapods

Meh, lets keep em in then.
