### ISSUE TITLE
No calendar events in 1.2

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#200]
Other TUM Online info is there, but no calendar events. Refresh button does not resolve the issue.

http://tca.exgen.io/scp/tickets.php?id=281

**Comment by mathiasquintero** [comment]
@mammuth what do you think? Parse Issue?
We ignore any entries without start, end, title, status, link or location.
https://github.com/TCA-Team/iOS/blob/master/TUM%20Campus%20App/CalendarManager.swift#L84

Perhaps some of these fields are indeed optional. I'll check what Android is doing in this scenario.

**Comment by mathiasquintero** [comment]
@pfent wait is anything required? 
https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/models/tumo/CalendarRow.java

**Comment by pfent** [comment]
The last functional change to that file was 4 years ago 🎉 
But yes, it seems all fields in the calendar rows are optional... Or someone couldn't figure out which were not and just defaulted them all to an empty string...

**Comment by kordianbruck** [comment]
So i observered this today: it was loading for ever and the calendar was really slow when swiping right/left. It showed no events. Then after like a minute or something suddenly everything clicked into place and the events showed. Also it was no longer laggy.
I don't know the code for this, but there is something really fishy here.

**Comment by kordianbruck** [comment]
@mathiasquintero right. Ye, we have a separate issue for that lag. 

But also the events didn't show with the girl that tried it out tonight. After jiggeling around and swiping they showed up after so time. So I would also think of an network issue.

**Comment by TG908** [comment]
Obsolete
