### ISSUE TITLE
Consider a Beta Test Program

### ISSUE THREAD

**Issue by mathiasquintero** [TCA-Team/iOS#201]
I've noticed that a lot of our issues happen because we're not testing enough due to time constraints.
Maybe be should consider opening up a beta trough TestFlight or Crashlytics.

Thoughts?

**Comment by TG908** [comment]
Testflight?

**Comment by kordianbruck** [comment]
Testflight. Its integrated with apple right?

**Comment by kordianbruck** [comment]
Well let's use that instead of third party then?

**Comment by mathiasquintero** [comment]
I was more worried about if it's worth the hassle than how to distribute it. But If you think it's a good idea, I think we can do it

**Comment by kordianbruck** [comment]
You should certainly do it. We do it for android as well. If there aren't any terrible bugs we only then publish the previous beta.

**Comment by mathiasquintero** [comment]
Ok. Sounds good. @mammuth @TG908 what do you guys think. 
Should we perhaps pospone the 1.3 release and just release a Beta?

If so how do we plan on getting Beta Testers?

**Comment by mammuth** [comment]
> If so how do we plan on getting Beta Testers?

We could add a hint at the bottom of the more view.

**Comment by mathiasquintero** [comment]
A puzzle to get to the Beta?
We are missing some Easter Eggs anyway

**Comment by mammuth** [comment]
Well we don't have that many users yet, I would actually make it easy to join the beta to get some people in. If we have the feeling there are enough beta testers we could make it harder (by don't displaying the into that obvious, a small puzzle or whatever).

**Comment by TG908** [comment]
How about inviting people when they send us a support ticket. They are motivated to help anyway.

**Comment by mammuth** [comment]
> How about inviting people when they send us a support ticket. They are motivated to help anyway.

Yep, good approach. I do the same with the Tank Navigator, works out great 👍 The support is also a good way for asking for a good rating if they enjoy the app 😊
We can probably add a ios-team signature on osTicket where those boilerplate stuff is filled in.

**Comment by kordianbruck** [comment]
@mammuth i think the iOS APP has 8k users ;-)

**Comment by mathiasquintero** [comment]
Not so small after all

**Comment by mammuth** [comment]
> @mammuth i think the iOS APP has 8k users ;-)

Yep, I know :wink: 
So 1% testers would be 80 people. Sure, there are not as many device / OS configurations as on Android, but still having 1% as testers is a quite high percentage I guess, whereas 80 people are not that many.

But nevertheless, I still propose putting an obvious option in there to see how many people opt in for the beta, how well we're able to manage the feedback and then optionally make the info less obvious after those insights.

**Comment by kordianbruck** [comment]
I think the settings will be just fine :o
will do the same on android
