### ISSUE TITLE
Easter Eggs!

### ISSUE THREAD

**Issue by mathiasquintero** [TCA-Team/iOS#203]
How did we release three versions without any?!?!?!

**Comment by TG908** [comment]
One should be on the tum logo

**Comment by kordianbruck** [comment]
![tumrainbow](https://user-images.githubusercontent.com/298860/32109802-07351056-bb36-11e7-9b94-4959c0d7d380.png)

If you click, switch it over to this ;)

**Comment by mathiasquintero** [comment]
Funky mode activated!!!
