### ISSUE TITLE
ASWeekSelector and others

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [TCA-Team/iOS#21]
Various compilation problems with ASWeekSelector, CalenderViewController AYSlidingPickerView, MCSwipeTableViewCell, Alamofire, MCSwipeTableViewCell, SWXMLHash, SwiftyJSON
Most errors include "no such module". Tried to "fix" them by committing them with //, but did not help 
![2016-11-03 22 30 53](https://cloud.githubusercontent.com/assets/20713070/19986109/ac8a33a0-a215-11e6-966d-fd0f3d29b745.png)
![2016-11-03 22 31 30](https://cloud.githubusercontent.com/assets/20713070/19986110/ac8e27bc-a215-11e6-82d8-b6febf8820ac.png)
![2016-11-03 22 31 47](https://cloud.githubusercontent.com/assets/20713070/19986111/ac920b0c-a215-11e6-959a-537530a7c56d.png)
![2016-11-03 22 31 57](https://cloud.githubusercontent.com/assets/20713070/19986112/ac940006-a215-11e6-9dcc-4e0fb3be900b.png)

**Comment by mathiasquintero** [comment]
@13XxM1CHA3lxX37 did you open the project or the workspace?

**Comment by mathiasquintero** [comment]
@13XxM1CHA3lxX37 did that work?

**Comment by mathiasquintero** [comment]
@13XxM1CHA3lxX37 please just tell me if it worked so that I can close this issue

**Comment by 13XxM1CHA3lxX37** [comment]
That's embarassing right now. That was the problem

**Comment by mathiasquintero** [comment]
please use the latest from master. I did find a few errors about 20 min ago
