### ISSUE TITLE
Implement tum newspread

### ISSUE THREAD

**Issue by TG908** [TCA-Team/iOS#210]
I think we should implement the slides from the [news screen](https://tum.newspread.de/page/newspreadLive) in the app. The api looks straight forward and easy to use: [rss](https://tum.newspread.de/page/newspreadLive/4.rss). Maybe using cards like [this](https://github.com/PaoloCuscela/Cards).

**Comment by TG908** [comment]
![slice1](https://user-images.githubusercontent.com/7985149/32683942-40e4ecfa-c67f-11e7-95ab-0873e7758593.png)

**Comment by TG908** [comment]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/7985149/32684003-dcb7143c-c67f-11e7-802c-7fb583bc0c5e.png">

**Comment by mathiasquintero** [comment]
Ewww: ```<content:encoded>&lt;img class='true reloader' height='480px' width='960px' src='https://storage.googleapis.com/tum-newspread-de/assets/e09d0063-af8c-463a-a54c-b69d829c1f91.jpeg' /&gt;</content:encoded>```

**Comment by kordianbruck** [comment]
Guys. This is part of the News API from tumcabe. Please don't parse any other endpoints other than tumcabe and tumonline. Everything should be cached on our server to reduce load on other services and be able to fix parsing problems without releasing a new version!

**Comment by mathiasquintero** [comment]
So I'd suggest we refactor our use of the news API first so that we can separate these by category.
See #43

**Comment by TG908** [comment]
Categories:

- News (TUM News, Fachschaft News)
- TU Film (TU Film)
- newspread (newspread)

**Comment by mathiasquintero** [comment]
@TG908 The Network part is implemented. You can use it but we're not receiving any of the newspread entries from the endpoint yet

**Comment by mathiasquintero** [comment]
Turns out most items from the news spread are pretty old and don't come by default.

@kordianbruck I only now noticed that Android uses the last id in sync. 
Should we do that? If so do we really have to store every news entry on the device?

**Comment by kordianbruck** [comment]
@mathiasquintero yes, that would be a great idea to reduce the amount of traffic and server load. Its really easy to implement. 
I wouldn't delete the entries. I don't think they delete the last id. So in case nothing new is there, they won't fetch anything. Newsspread is unfortunately broken right now. I'll have to check the cronjob for that as well.

**Comment by mathiasquintero** [comment]
@kordianbruck Sounds good.
I could recreate that behavior with this:

```swift
    func fetch(from news: String) -> Response<[News]> {
        return config.tumCabe.doObjectsRequest(to: .news,
                                               arguments: ["news" : news],
                                               maxCacheTime: .forever).flatMap { (news: [News]) in
            
            guard let last = news.last else {
                return .successful(with: news)
            }
            return self.fetch(from: last.id).map { news + $0 }
        }
    }
    
    func fetch(maxCache: CacheTime) -> Response<[News]> {
        return fetch(from: "1").map { $0.sorted(descending: \.date) }
    }
```

However, this will always fetch all the News Items. Or we can make it only fetch `/news/` the first time

```swift
    func fetch(maxCache: CacheTime) -> Response<[News]> {
        return fetch(from: "").map { $0.sorted(descending: \.date) }
    }
```

**Comment by kordianbruck** [comment]
@mathiasquintero probably the second is the better idea.

I've fixed the newsspread cronjob partially. Their RSS Feed is just a real mess. I've followed up with them and am awaiting an response within the next days.

**Comment by mathiasquintero** [comment]
Ah yes. The links that are not valid URLs. Beautiful implementation of an RSS Feed
