### ISSUE TITLE
Silent Service

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#22]

**Comment by TheZoker** [comment]
http://stackoverflow.com/questions/10371312/mute-silence-an-ios-device-programmatically

**Comment by mathiasquintero** [comment]
@TG908 why did you close this? I don't think we've done this

**Comment by kordianbruck** [comment]
Background services are a no go on iOS.

**Comment by mathiasquintero** [comment]
Makes sense.

**Comment by TG908** [comment]
Yeah thats pretty much it. @mammuth and me were going through all the issues on the last meeting and I simply forgot to add a message.
