### ISSUE TITLE
Separate Cards for News, TU Film and Newspread

### ISSUE THREAD

**Issue by TG908** [TCA-Team/iOS#220]
I'd like to have, different cards for the above news sources. In the current implementation only the title and titleColor are changed. However I want those 3 cell to have each a different UI. Thats's why I need an individual card class for each of those cards.

**Comment by kordianbruck** [comment]
@TG908 @mathiasquintero the /kino endpoint is now working again with all the latest movies.

**Comment by mathiasquintero** [comment]
Tagging this for the 1.4 to be included as part of the new UI

**Comment by TG908** [comment]
Implemented i #251
