### ISSUE TITLE
Mensa Prices

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#221]
User Feedback:

"Es wäre nice, wenn man die Preise der Gerichte in der Mensa-Ansicht sehen könnte. Aktuell funktioniert das noch nicht, in der Android App wurde das umgesetzt."

=> We need a backend api for this first. Android has hardcoded those.

**Comment by mathiasquintero** [comment]
iOS has these also hardcoded:

https://github.com/TCA-Team/iOS/blob/master/TUM%20Campus%20App/CafeteriaConstants.swift

**Comment by TG908** [comment]
Can confirm I personally typed them in by hand one by one

**Comment by TG908** [comment]
Doesn't the Mensa Stammgelände have no prices because you have to mix n match your food. For Garching some prices appear but not all. Seems like the API is a bit incomplete

**Comment by thellmund** [comment]
Server issue.
