### ISSUE TITLE
Use app.tum.de

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#234]
I will be making this domain the default. Please make sure you use it everywhere in the app.
Especially HTTPS pinning might be a problem.

**Comment by mathiasquintero** [comment]
The default for API or only links.
So far we're not doing any HTTPS pinning. 
So unless you want us to have extra checks, it should be a one liner!

In fact Transport Security is probably turned. I get the feeling something in there is HTTP only.

**Comment by mathiasquintero** [comment]
@kordianbruck is the Android app pinning the certificate. 
If so this is probably desired behavior for iOS?

**Comment by mathiasquintero** [comment]
If we want to pin the certificate we will have to let `TumCabeAPI` conform to `CustomAPI`, include the certificate in the bundle and implement `urlSession(_:task:didReceive:completionHandler:)`

**Comment by kordianbruck** [comment]
For everything. Links & API.
Yes, Android is pinning the root cert.

**Comment by mathiasquintero** [comment]
@kordianbruck ok. I just implemented a first draft of the root cert pinning.

Just to be clear I should be pinning using the sha256 fingerprints of the three certificates:

```
let fingerprints = [
            "D0 CE CA 13 E4 0A FF 49 F6 8C 2B 95 8A 66 26 89 5A 41 4F AA 47 55 F6 DC 03 7F 05 3B 5F 15 DF 1C",
            "25 84 7D 66 8E B4 F0 4F DD 40 B1 2B 6B 07 40 C5 67 DA 7D 02 43 08 EB 6C 2C 96 FE 41 D9 DE 21 8D",
            "06 87 26 03 31 A7 24 03 D9 09 F1 05 E6 9B CF 0D 32 E1 BD 24 93 FF C6 D9 20 6D 11 BC D6 77 07 39",
            ]
```

and refuse any connection if any of these is missing

**Comment by kordianbruck** [comment]
@mathiasquintero it does not make sense to pin the automatically renewed certificate on the very last level. You can Pin DST Root CA X3 and LE Authority X3. Apart from that I wouldn't pin anything else.

As for other services: no, we don't control those certificates and that may just lead to too many problems.
