### ISSUE TITLE
Study Rooms

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#24]
https://campus.tum.de/tumonline/wbrisweb.status_mobile_mi

**Comment by TheZoker** [comment]
https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/activities/StudyRoomsActivity.java

**Comment by kordianbruck** [comment]
You can find the API at: http://www.devapp.it.tum.de/iris/ris_api.php

**Comment by kordianbruck** [comment]
@mammuth will we be able to finish this till the next milestone @ 20.04 ?

**Comment by mammuth** [comment]
The functionality is ready, it was @mathiasquintero who didn't like my absolutely sexy design, as stated in the PR #49. 

So we can surely make it until the next release I think.

**Comment by TG908** [comment]
Implemented
