### ISSUE TITLE
Implement TUM Alarmierungssystem

### ISSUE THREAD

**Issue by TG908** [TCA-Team/iOS#241]
@kordianbruck  Does our backend support [APNS](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html#//apple_ref/doc/uid/TP40008194-CH8-SW1)?

**Comment by TG908** [comment]
duplicate

**Comment by kordianbruck** [comment]
@TG908 no, we are using Firebase Cloud Messaging. Please see #9
