### ISSUE TITLE
Set a proper User Agent for API Calls

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#243]
In Android we use the following:
> TCA Client 1.5.3/521  

Please update your useragent in all api requests to something more useful than:
>Campus/10 CFNetwork/894 Darwin/17.4.0  

We for sure need to know what version is connecting.

**Comment by TG908** [comment]
What does 521 at the end mean?
I think we should differentiate between android and ios user agents so android would be

> TCA Android 1.5.3/521


and ios would be

> TCA iOS 1.3.1/521

**Comment by kordianbruck** [comment]
Its the build Version. Yes, you are right, please include iOS in the string
