### ISSUE TITLE
MVV malfunction card

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#25]

**Comment by TheZoker** [comment]
https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/cards/MVVCard.java

**Comment by kordianbruck** [comment]
This is not the MVV Card but rather a normal News Card

**Comment by lukaskollmer** [comment]
#141 only implements nearby stations and upcoming departures, it does not implement a news card

**Comment by mammuth** [comment]
Malfunctioning info isn't included in the news api endpoint anymore. According to the android team, people didn't use the feature, so let's not implement this for now.
