### ISSUE TITLE
Update copyright throughout the application

### ISSUE THREAD

**Issue by thellmund** [TCA-Team/iOS#253]
In some classes, we have copyright that points to chair 1 (Applied Software Engineering). 
It should use GPL v3: https://github.com/TCA-Team/iOS/blob/master/LICENSE

The copyright at the top of all classes should be updated accordingly.

See @kordianbruck’s comment for more info: https://github.com/TCA-Team/iOS/pull/251/files#r187782101

**Comment by TG908** [comment]
implemented in #251
