### ISSUE TITLE
Wrong height of navigation bar

### ISSUE THREAD

**Issue by thellmund** [TCA-Team/iOS#255]
When opening the app, the navigation bar is displayed with a wrong height. It stays like this until you scroll the CollectionView.

![simulator screen shot - iphone 7 plus - 2018-06-14 at 14 17 12](https://user-images.githubusercontent.com/11819826/41411607-bbd00d52-6fdd-11e8-9cc7-bdf2b45682c3.png)

**Comment by TG908** [comment]
The animation for the search bar is also buggy...

**Comment by thellmund** [comment]
Fixed in #258.
