### ISSUE TITLE
Plans

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#26]
- MVV Tram
- MVV complete
- Campus Garching
- Campus Klinikum
- Campus Olympiapark
- Campus Olympiapark Hallenplan
- Campus Arcisstraße
- Campus Weihenstephan

**Comment by TheZoker** [comment]
Images with: https://developer.apple.com/reference/uikit/uiimageview
PDF with: https://developer.apple.com/reference/uikit/uiwebview

**Comment by kordianbruck** [comment]
Please make sure to use the same procedure as with Android: download the files interactively and do not bundle them with the app, so we don't run into any legal hicups

**Comment by mathiasquintero** [comment]
I don't understand what this means. You mean like the maps for the places?

**Comment by kordianbruck** [comment]
@mathiasquintero these are the plans of the MVV that are implemented in the Android version

**Comment by TG908** [comment]
This feature has little to none to do with the university. Also this is not used too much in Android - so remove there as well
