### ISSUE TITLE
Intelligently scheduled notifications (cafeteria, tuitions)

### ISSUE THREAD

**Issue by thellmund** [TCA-Team/iOS#268]
**Problem today**
In order to retrieve any kind of information, the user needs to open the app. 

**Idea**
Like the Android app ([see here](https://github.com/TCA-Team/TumCampusApp/pull/879)), we can offer proactive information to the user. This includes: 
1. a notification about the cafeteria menu, recurring each weekday at 11am
2. notifications about tuition fees before the due date
3. notifications with the latest news

To realize this, we’d need to periodically fetch information and schedule their presentation as a notification accordingly.

**Comment by AW-tum** [comment]
All notifications will be handled in https://github.com/TUM-Dev/Campus-iOS/issues/360
