### ISSUE TITLE
Fix Room Finder Features to use the new API

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#28]
- [x] Search view with resultlist
- [x] Details view with map (switchable: Munich, Campus, building)

**Comment by mathiasquintero** [comment]
This is already implemented

**Comment by mathiasquintero** [comment]
@kordianbruck was the RoomFinder API deprecated? It doesn't seem to be working?

**Comment by kordianbruck** [comment]
The roomfinder is implemented within the tumcabe API. No idea, if you already implemented that one or the legacy version of it.

**Comment by mathiasquintero** [comment]
I was using http://vmbaumgarten3.informatik.tu-muenchen.de/roommaps/room/search?&s=<ROOM>

**Comment by kordianbruck** [comment]
Yeah, thats the legacy one :tada:

**Comment by mathiasquintero** [comment]
Was the model changed? Or do I just have to change the URL?

**Comment by kordianbruck** [comment]
The guys who implemented that, kinda hacked it together here: https://github.com/TCA-Team/TumCampusApp/blob/32e18cf0e0647a6168c2a2dcd2afb0a2442b41ef/app/src/main/java/de/tum/in/tumcampusapp/tumonline/TUMRoomFinderRequest.java

(I know its a mess)

**Comment by mathiasquintero** [comment]
It's reverse engineering time!!! Again.
