### ISSUE TITLE
Split storyboard into multiple files

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#32]
I'd like to refactor the storyboard into multiple files to prevent merge conflicts in the future. Any objections @mathiasquintero?

**Comment by mathiasquintero** [comment]
go right ahead ;) Just tell us all so that no one touches the storyboards

**Comment by mammuth** [comment]
Beside the setup wizard most of the scenes are highly coupled to others (at least most of the detail scenes are referenced from multiple scenes, like eg. firstly by the card scene and secondly by the search scene).
As a result it's kind of hard to break the scenes down to storyboards so that there is little coupling between the boards. 

A possible refactoring might be to create a storyboard for every view we have (card view, movie detail view, tution detail view, calendar detail view, ...) and place the storyboard-file in the corresponding folder.

This way storyboards are not bundled according to user flow, but by features.

It'd probably make it harder to navigate and understand the flow, but prevents merge conflicts and seems to be a good compromise.

**Comment by mathiasquintero** [comment]
Sounds good. You're basically saying we turn Storyboards into defacto XIB files
