### ISSUE TITLE
TU-Movie card not showing picture

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#41]
<img width="360" alt="bildschirmfoto 2016-12-16 um 13 37 53" src="https://cloud.githubusercontent.com/assets/3121306/21263052/dfc38a1e-c394-11e6-9d6a-bccd6838394b.png">

**Comment by mammuth** [comment]
Ah, looks like that's a bug in the API: 
https://tumcabe.in.tum.de/File/kino/The%20Hateful%208.jpg
cc @kordianbruck

**Comment by mammuth** [comment]
I guess this was fixed in #78, right? Reopen if that's not the case. 

Btw, @TG908 when you add a "fixes #X" to the commit message body of eg. the first commit to a branch, the issue gets closed automatically when merging the branch into master :+1:

**Comment by TG908** [comment]
The movies still appear in the news card but I fixed the scaling and position of the image view
