### ISSUE TITLE
Refactor use of TUMCabe news API?

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#43]
The news API (https://tumcabe.in.tum.de/Api/news/) currently contains 3 sources:
- TUM news
- TU movie
- ~~MVG Störungsticker~~

In Android the approach looks like this as far as I understand:
- Fetch items from the news/ endpoint once
- Get the closest TUM news and display it as card
- Get closest movie news and display as card
- Get closest Störungsticker news and display as card

In iOS we currently just display the most recent news in the news card and the most recent TU movie in the movie card. However the movie is managed by the MovieManager (and it made it's own request to the kino/ API endpoint to build that card).

Maybe we should adopt the design of the Android app and build 3 cards (movie, news and MVG Störung) via one single news/ call?
The kino/ endpoint is then used in the detail view of a movie.

Related "MVV malfunction card" #25

**Comment by mathiasquintero** [comment]
To make the design of the managers as easy as possible, perhaps we should introduce an enum to the news for this. Or does the model of the news vary?

**Comment by mammuth** [comment]
> Or does the model of the news vary?
I guess we can keep one generic news model for all three types of news - at least that's what the API seems to be doing.

**Comment by kordianbruck** [comment]
![screenshot from 2016-12-16 23-17-33](https://cloud.githubusercontent.com/assets/298860/21280376/e6b420da-c3e5-11e6-964d-a68f9c201d0f.png)

Please make this dynamic. We have more than three news sources and there will be more. The Fachschaft MPI and Maschinenbau will be added in the coming weeks.

**Comment by mathiasquintero** [comment]
@kordianbruck what exactly do you mean by dynamic? My question is how does the model look like? Will it change when it's a MPI news item? (are there extra properties for those?)

**Comment by kordianbruck** [comment]
No, there will not be extra fields but more sources. For each source the latest card should be displayed. Except in the tufilm, it should be the next card.

**Comment by kordianbruck** [comment]
@mammuth Störungsticker proved to not be useful and was removed two months ago.
