### ISSUE TITLE
Better explanation of the authorization step

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#45]
In Android there is a image showcasing what to do in TUMOnline, we should probably add similar explanations before releasing it.

<img width="375" alt="bildschirmfoto 2016-12-17 um 11 14 28" src="https://cloud.githubusercontent.com/assets/3121306/21286063/1036898e-c44a-11e6-8a07-eabc04c05851.png">

**Comment by kordianbruck** [comment]
Please also take into account, that it is possible to activate via the link send to the email address
