### ISSUE TITLE
Allow non TUM Students to use the app

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#64]
We need to allow to use the App without the TUM ID asap.

Who has time to do this in the current week?

**Comment by mammuth** [comment]
Maybe also add 1-2 additional cards with Infos that are available without a lrz account. 

How about a static card with links to resources for interested pupils about the studies at the TUM? This card can just be hidden when there is a logged in user.

**Comment by mathiasquintero** [comment]
@mammuth I love the idea of tum.sexy. Where can I just get the links without the page?

**Comment by kordianbruck** [comment]
Check the redirection/ folder in the repo. There is a routes.php file there containing only the redirections

**Comment by mathiasquintero** [comment]
Yeah, but how can I best fetch them from the phone?

**Comment by kordianbruck** [comment]
We could add an endpoint that would return the json? Would that work?

**Comment by mathiasquintero** [comment]
That would be awesome

**Comment by mammuth** [comment]
I'm off for work today, Kordian can you do the json endpoint?

**Comment by kordianbruck** [comment]
Yup, will do in 45 mins

**Comment by kordianbruck** [comment]
e voilá: http://json.tum.sexy/
