### ISSUE TITLE
Crash: Plus Sign

### ISSUE THREAD

**Issue by melloskitten** [TCA-Team/iOS#65]
Hi! I'm running iOS 10.2.1 on my IPhone and ran into this issue.

Tapping on the + sign on your profile leads to the app crashing after 2-3 seconds

**Comment by kordianbruck** [comment]
@melloskitten thanks for reporting this - we will look into it shortly

**Comment by mathiasquintero** [comment]
That was quick. I think the API might have changed since iOS 10

**Comment by mathiasquintero** [comment]
I'm not at my computer but my best guess is we're missing the privacy description string for getting access to the devices contacts.

We have to added it to the info.plist

**Comment by kordianbruck** [comment]
#66

**Comment by mammuth** [comment]
Cool! 

Btw, you can auto-close issues on Github by using phrases like "closes/fixes #X" in the commit message.

**Comment by melloskitten** [comment]
wooo thank you! Didn't know that! :dancer:
