### ISSUE TITLE
Spinner Bug when there are no cards in Featured Tab 

### ISSUE THREAD

**Issue by melloskitten** [TCA-Team/iOS#67]
I've run across a minor issue - If you have no cards enabled on your Featured Tab, and pull the screen down to refresh, the spinner simply keeps spinning forever. And if you decide to change the tab while the spinner is there, then return to the Featured Tab again, the spinner will stay in its place, frozen, and you are unable to refresh again. 

Using IPhone 6, iOS 10.2.1

**Comment by TG908** [comment]
#75

**Comment by TG908** [comment]
Fixed
