### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#69]
Heya,

so I just wanted to ask everyone to specify what their license ideas are. I saw a few comments like 
```
//  Copyright © 2016 LS1 TUM. All rights reserved.
```
which I'm not sure what *LS1* exactly is. I've currently release it under GPLv3 - is everyone alright with that?

**Comment by mammuth** [comment]
So I'd say the best idea is to have everyone who contributed so far to acknowledge that the code will be transitioned to a GPLv3 license here. 

Afterwards we add the correct license header to all files.

I'm fine with having the TUM Campus App for iOS under the GPLv3 license.

**Comment by mathiasquintero** [comment]
LS1 stands for Lehrstuhl 1. I was in their enterprise team back when I started the project and Xcode autocompletes with the name of the Team. We should update the headers.

I will need to reread the terms of GPLv3 to see if I'm ok with it :)

**Comment by melloskitten** [comment]
Thanks for mentioning me too haha :) I agree with the proposal to use the GPLv3 license. When should we update the Headers accordingly?

**Comment by kordianbruck** [comment]
Quoting from https://choosealicense.com/licenses/gpl-3.0/
> Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.

Basically: do what you want, but need to publish source under same license

**Comment by TG908** [comment]
The license seems to have changed can we close this?

**Comment by kordianbruck** [comment]
No, we need to update the Files with the correct license header. Plus still waiting for @mathiasquintero

**Comment by mathiasquintero** [comment]
Oopss sorry. Hehe. Forgot to answer. Yeah I read it. I'm cool
