### ISSUE TITLE
Poor performance due to missing caching

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#72]
So from what I've tested the app does not seem to cache most of the data. Most noticebly it happend several times that the app was unresponsive due to load some data (10-20 seconds in the case of the calendar).

We will run into problems with the TUM. Especially the calendar uses a lot of resources on their mainframe. That should be updated once every 7 days or so at the very most! (Ask @xsrf for more details on this)

Please take a look at the Androids caching mechanics: https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/managers/CacheManager.java

**Comment by TG908** [comment]
We also need a mechanism to detect if the user enabled the token to access the calendar. And remind the user to enable it

**Comment by mathiasquintero** [comment]
The calendar is the only thing being cached

**Comment by TG908** [comment]
@mathiasquintero If the user forgets to enable calendar access on the first app launch he has to wait for 7 days to get a calendar?

**Comment by mathiasquintero** [comment]
No. The Manager checks the last modified date of the file. If there's no file it tries to fetch the calendar again

**Comment by TG908** [comment]
Ok my calendar might have another issue then...

**Comment by mathiasquintero** [comment]
I'll check it anyway. Maybe the API has changed somehow

**Comment by TG908** [comment]
I did some performance analysis:

**Comment by kordianbruck** [comment]
yea, we should cache all the things!

**Comment by TG908** [comment]
sure

**Comment by kordianbruck** [comment]
If you gonna spam the TumOnline API, they will turn it off for good. @xsrf right? :skull_and_crossbones:

**Comment by mathiasquintero** [comment]
I would move this to the release after 1.1. It's still High Prio. But it will require rethinking our architecture to add a caching layer without too much copy and paste
