### ISSUE TITLE
Card Design Update

### ISSUE THREAD

**Issue by TG908** [TCA-Team/iOS#82]
What do you guys think of adding labels to the cards with the card type: e.g. Mensa, News, TU Film ...

![simulator screen shot 16 04 2017 23 31 59](https://cloud.githubusercontent.com/assets/7985149/25074643/79ce2bb2-2300-11e7-9c73-7c188da434b8.png)

![simulator screen](https://cloud.githubusercontent.com/assets/7985149/25074685/c0b2ad4a-2301-11e7-8c90-5c40f82e622f.png)

**Comment by mammuth** [comment]
I like the idea! 

But I'd suggest a much more subtle, small, light grey text-only indicator maybe at the bottom right?

**Comment by mathiasquintero** [comment]
We could try that. If it's greyed out it should be on the right. Maybe with an Icon

I personally think this one looks really nice. Perhaps a little shadow could help. And also fix the top layout constraints to be slightly more apart from the label.

**Comment by TG908** [comment]
@mammuth I wanted to bring in some more colors into our UI design. Because I think it looks a bit dull and monotone at the moment..

**Comment by mammuth** [comment]
> @mammuth I wanted to bring in some more colors into our UI design. Because I think it looks a bit dull and monotone at the moment..

Ha, I felt the same, so I made the study rooms loud and colorful. Which obviously was to much and @mathiasquintero didn't enjoy as much as I did. 
Get your point. Sounds legit. 👍

**Comment by TG908** [comment]
![simulator screen shot 16 04 2017 23 31 59](https://cloud.githubusercontent.com/assets/7985149/25074707/4a35928a-2302-11e7-85ff-4650a1cfdcff.png)

**Comment by TG908** [comment]
I could change it to one single color maybe...

**Comment by mathiasquintero** [comment]
@mammuth I didn't like it because it was too dominant and didn't go with the design we had going on. This does match

**Comment by TG908** [comment]
Ok ill try putting this into code soon with:
-  Labels on the left
- One single color

**Comment by mathiasquintero** [comment]
I actually like the colors. Just be careful about your color choices.

**Comment by TG908** [comment]
The content should also be more colorful:
- green text on prices for mensa dishes
- red tution fee balance if > 0
- green tution fee balance if <= 0
-Maybe: color deadline green if 2+ months; left yellow < 1 month left; red one week left

**Comment by TG908** [comment]
I really like this [desing](https://github.com/Ramotion/folding-cell) but im not sure if it fits into this app

**Comment by kordianbruck** [comment]
@TG908 I like the design! I think it fits.

Just make sure to open up an issue in the Android Repo so we stay on the same page. Thanks!

**Comment by TG908** [comment]
Will do when design is final

**Comment by TG908** [comment]
Thats how it looks at the moment:

![simulator screen shot 17 04 2017 21 53 48](https://cloud.githubusercontent.com/assets/7985149/25102319/55a6e7de-23b8-11e7-8243-754b297b1ed9.png)

**Comment by kordianbruck** [comment]
It looks good! What about the idea in comment https://github.com/TCA-Team/iOS/issues/82#issuecomment-294378573 ?

**Comment by TG908** [comment]
Im not sure how long such a drastic design change will take. Depending on how long it takes i'd say we should do the swap in Version 1.1 or 2.0 if every one agrees.

**Comment by kordianbruck** [comment]
Why will this be drastic? Because we are switching out the cards system?

**Comment by TG908** [comment]
Well we could try. I'm in.

**Comment by kordianbruck** [comment]
I mean if you have the time - go for it! The thing looks awesome. One drawback of course is that if that lib is not maintained any longer you might be stuck with it. @mammuth @mathiasquintero @melloskitten what do you guys think?

**Comment by TG908** [comment]
I created a PR #97 for the new card label. If this is still needed. I will start working on adopting the new design.

**Comment by TG908** [comment]
@kordianbruck So i tried the FoldingCell. It works however they did not include the table view design from the image. They only included the FoldingCell. If we want this to work we have to put a whole lot of work into this (Designing the new cards, the new interface inside the cards, ...). Check out my branch if you want to see it working (kinda).

**Comment by mathiasquintero** [comment]
Yeah. The guys at ramotion make pretty videos. But their code isn't very good

**Comment by TG908** [comment]
Yeah i had a divide by zero when I set it up with the default values :S

**Comment by TG908** [comment]
I got it but i think it doesnt look quite right: I need to work on the background and cards
![simulator screen shot 20 04 2017 22 19 09](https://cloud.githubusercontent.com/assets/7985149/25250863/a96de7b2-2617-11e7-8383-ff1abbd2d712.png)
![simulator screen shot 20 04 2017 22 19 02](https://cloud.githubusercontent.com/assets/7985149/25250864/a99170f6-2617-11e7-94b2-ad06cf4bfbb1.png)

**Comment by kordianbruck** [comment]
I mean it looks wow. 

If your experience with the code is so bad tho, we might just not want to use it then. So if you say a lot of work, then I mean I trust your judgement. I'd rather have that time invested in some more features (Chat, MVV, etc.). For now: keep it on a branch and we can revisit it in 2-3 months after the bugfix release. 

@mathiasquintero lets merge the current PR and have that in for the next release. That looks quite promising.

**Comment by mathiasquintero** [comment]
I think that if we add this and maybe the book rental card we can release the 1.1. And leave the rest for the 1.2

**Comment by TG908** [comment]
@kordianbruck the code is not that bad, the default values were the only problem I had, Performance is great on both iPhone 5s and iPhone 7. With a lot of work I mean:

- [ ]  restructure control flow of the UI
- [ ] improve card UI

**Comment by kordianbruck** [comment]
I see - okay, lets move this to 1.2.

I actually like a white / grey / black background without much graphics.

**Comment by TG908** [comment]
Me too

**Comment by TG908** [comment]
Got a new mockup:

![a99170f6-2617-11e7-94b2-ad06cf4bfbb1](https://cloud.githubusercontent.com/assets/7985149/25354342/ed46e704-2932-11e7-9cb8-f5ba7fd23fba.png)

To Do:

- [ ] Add shadows
- [ ]  Add stuff to the container View
- [ ] hook up all the labels to the code

**Comment by TG908** [comment]
Card View looks really dope right now

**Comment by TG908** [comment]
implements #76

**Comment by TG908** [comment]
done
