### ISSUE TITLE
Release Party - 1.1

### ISSUE THREAD

**Issue by mathiasquintero** [TCA-Team/iOS#83]
@mammuth and I were thinking it's about time to do a release Party!

I'd say that after the next release of 1.1 with all the bug fixes we can all celebrate together!

Since @kordianbruck is always so eager to organize things, I suggest he should be in charge.

**Comment by kordianbruck** [comment]
Sure! Maybe i can organize a pizza party? Other ideas / suggestions?

**Comment by mammuth** [comment]
cc @TCA-Team/ios (so all are notified :) )

**Comment by kordianbruck** [comment]
Lets do it next Monday 1.5. Please vote for either of these four locations:

1. Garching MI
2. Stammgelände (Does someone aware of any rooms that are accessable?)
3. Karlstrasse in the office
4. ??? Suggest something

Program: order pizza and code for 3-4 hours. Get crazy!

@TCA-Team/ios @TCA-Team/android @TCA-Team/backend

**Comment by mammuth** [comment]
1. Garching MI
4. Maybe C2?

**Comment by mathiasquintero** [comment]
Is the C2 open on the 1st? Because then beer sounds like a plan

**Comment by kordianbruck** [comment]
I wrote them a mail, but sure, lets do that then! (Food ain't great there, but they have decent beeeeeeer :beers: )

**Comment by kordianbruck** [comment]
C2 is closed on monday @mammuth @mathiasquintero - so whats it gonna be?

**Comment by mammuth** [comment]
I cast my vote for Garching MI. 

What about all others, use your voice! But wisely. @TCA-Team/ios @TCA-Team/android

**Comment by mathiasquintero** [comment]
MI works great for me

**Comment by TG908** [comment]
MI

**Comment by TG908** [comment]
Which room?
What time?

**Comment by mammuth** [comment]
16:00! :tada:
And maybe just meet at the Magistrale and then find out where to stay best.

**Comment by kordianbruck** [comment]
@TG908 we are in 00.08.036
