### ISSUE TITLE
Prettify time until next lecture

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#89]
![image](https://cloud.githubusercontent.com/assets/3121306/25084556/760c3d54-235d-11e7-8a33-faec4b16c95f.png)

245 hours is no really useful information. Maybe we could say something like 10 days and 2 hours?

Or just completely hide this information as long as it's more than 24 hours or something like that?

**Comment by TG908** [comment]
#91

**Comment by TG908** [comment]
Done
