### ISSUE TITLE
Refactor URLs

### ISSUE THREAD

**Issue by mathiasquintero** [TCA-Team/iOS#90]
Refactor the creation of URLs by writing all the baseURLs in a JSON file . And finally get rid of all the warnings from Sonarqube

**Comment by mathiasquintero** [comment]
Sorry I closed the wrong issue 🙃

**Comment by rodalfus** [comment]
Is this still needed? If so, I'd like to take care of it.

**Comment by mathiasquintero** [comment]
I already started this. I was refactoring the singleton out of the process ;) 
But you can check out my branch: https://github.com/TCA-Team/iOS/tree/mathias/network-refactor
If you want to help out.

**Comment by rodalfus** [comment]
If I can allocate time for it myself, I will definitely check it out.
