### ISSUE TITLE
Add a card for the MI Bistro

### ISSUE THREAD

**Issue by TG908** [TCA-Team/iOS#93]
It would be nice if we could somehow use the mi bistro menu from tum.sexy. And either integrate it into cafeteria card or create a new card

**Comment by kordianbruck** [comment]
Yea, we really actually want to serve one endpoint from the main Tumcabe API that allows for that. 

Check: https://github.com/TCA-Team/TumCampusApp/issues/127

**Comment by TG908** [comment]
Duplicate
