### ISSUE TITLE
Annoucement Poster

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#94]
We will have a grant from the F13 chair to print a few posters for the new iOS release.

Someone up to designing it? I think I have the PSD for the Android one somewhere... Let me know.

**Comment by TG908** [comment]
Some ressources: https://developer.apple.com/app-store/marketing/guidelines/#

**Comment by TG908** [comment]
I cannot design this on my own, but i'd like to help. Can you post the old psd and maybe an image of the poster. Also which format is the poster gonna be? I only have Affinity Designer no Adobe Products.

**Comment by kordianbruck** [comment]
The old Poster can be found here: https://tumcabe.in.tum.de/downloads/poster.png
You can use GIMP for editing PSD files. I have it at home I think - I can send it by Wednesday or something. 

You can do for A0 if you want, we can always size it down to A1/A2 - not sure what they can print at the RBG.

**Comment by TG908** [comment]
Thats my first basic draft: 

![tca poster](https://cloud.githubusercontent.com/assets/7985149/25095102/6eb3d14c-239a-11e7-969f-cc493d5894f0.png)

**Comment by TG908** [comment]
Now I need your input (I know its very plain :D):

**Comment by kordianbruck** [comment]
- Store icons should be both German or both English

The rest ist nice. Needs to actually be designed tho :grin:

**Comment by TG908** [comment]
Should i also link to the  [windows phone campus app](https://www.microsoft.com/de-de/store/p/tum-campus-app/9nblggh0fssk). I can sneak that into the qr so that when a windows phone scans the qr they will be redirected to the windows phone store

**Comment by kordianbruck** [comment]
Ah yes: please make that QR Code point to the official website: https://tumcabe.in.tum.de/landing/

(If someone is good with PHP we can do the redirect there as well)

**Comment by TG908** [comment]
The QR already redirects ios to appstore android to google play and any other os to the website

**Comment by kordianbruck** [comment]
And what website is that redirection running on / which service? I won't print something, that won't work in 2-3 years because some website stopped working. So: no URL shortening or other magic please.

**Comment by TG908** [comment]
http://onelink.to

**Comment by kordianbruck** [comment]
yea, please don't. :+1:

**Comment by TG908** [comment]
Ok php then, can we use goo.gl for analytics?

**Comment by kordianbruck** [comment]
We have analytics on the webserver already set up. Just put in tumcabe.in.tum.de in there and we can work from there in the https://github.com/TCA-Team/Backend project.

**Comment by TG908** [comment]
Ok
