### ISSUE TITLE
Host SonarQube ourselves

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/iOS#99]
Currently our sonar-server is using sonarqube.com. However, sonarqube.com is a bit limited, as you eg. cannot add or change quality profiles. As a result I think there is no way to disable rules like _"Refactor your code to get this URI from a customizable parameter"_ or set certain rules as not critical.

Furthermore, on a dedicated install, we could use a custom swift quality profile like the following instead of sonars one, which provides some more rules: https://github.com/Backelite/sonar-swift

If we feel over time that sonarqube and the GitHub bot are valuable to the development of the project, we might host it somewhere to have increased flexibility and also make it available to the android repo.

**Comment by TG908** [comment]
not gonna happen
